# lib/expedition/notes.py
"""Expedition Field Journal — records per-run markdown notes.

One markdown file per expedition run, written to data/expeditions/.
Each file accumulates entries from all chips as the run progresses.
Entries are appended atomically (open/append/close) so concurrent
chip workers don't need coordination beyond the OS-level file append.

Public API:

    journal_entry(run_number, chip_id, model_id, task, sample_desc,
                  first_voice_text, compile_time_s, score_pts, project_dir)

    → Path to the journal file (created or appended).
"""
from __future__ import annotations

import datetime
import os
from pathlib import Path


# Decorative ASCII elements in the Tenstorrent palette (no right-side borders).
_ENTRY_SEP = "────────────────────────────────────────────────────────────────"


def _journal_path(run_number: int, project_dir: str | Path) -> Path:
    """Return the path to the journal file for a given run number."""
    base = Path(project_dir) / "data" / "expeditions"
    base.mkdir(parents=True, exist_ok=True)
    return base / f"expedition_{run_number:04d}.md"


def journal_entry(
    run_number: int,
    chip_id: int,
    model_id: str,
    task: str,
    sample_description: str,
    first_voice_text: str,
    compile_time_s: float,
    score_pts: int,
    project_dir: str | Path = ".",
) -> Path:
    """Append one First Voice entry to the run's journal file.

    Creates the file with a header on the first entry, then appends
    subsequent entries.  File is opened in append mode so concurrent
    workers writing from different chips don't corrupt each other's output
    (POSIX append writes are atomic for small writes).

    Args:
        run_number:        Sequential expedition run number.
        chip_id:           Zero-based chip index that produced this result.
        model_id:          HuggingFace model identifier.
        task:              HuggingFace pipeline task string.
        sample_description: Human-readable label for the sample used.
        first_voice_text:  The decoded inference output (the model's "first voice").
        compile_time_s:    Wall-clock seconds spent in forge.compile().
        score_pts:         Points awarded for this compilation event.
        project_dir:       Repo root; defaults to cwd.

    Returns:
        Absolute path to the journal file.
    """
    journal = _journal_path(run_number, project_dir)
    now = datetime.datetime.now(datetime.timezone.utc)
    timestamp = now.strftime("%Y-%m-%d %H:%M:%S UTC")

    with open(journal, "a", encoding="utf-8") as f:
        # Write header on first access (when file is empty or new).
        if journal.stat().st_size == 0 if journal.exists() else True:
            try:
                size = journal.stat().st_size
            except FileNotFoundError:
                size = 0
            if size == 0:
                f.write(f"# Expedition Field Journal — Run #{run_number:04d}\n\n")
                f.write(f"*Generated by tt-forge-compiletron · {now.strftime('%Y-%m-%d')}*\n\n")
                f.write(f"{_ENTRY_SEP}\n\n")

        # Write the entry.
        f.write(f"## ★ {model_id.split('/')[-1]}\n\n")
        f.write(f"**Model:** `{model_id}`  \n")
        f.write(f"**Task:** {task}  \n")
        f.write(f"**Chip:** {chip_id}  \n")
        f.write(f"**Compiled in:** {compile_time_s:.1f}s  \n")
        f.write(f"**Score:** +{score_pts} pts  \n")
        f.write(f"**Timestamp:** {timestamp}  \n\n")
        f.write(f"**Sample input:** *{sample_description}*\n\n")
        f.write(f"**First Voice:**\n\n")
        f.write(f"> {first_voice_text.strip()}\n\n")
        f.write(f"{_ENTRY_SEP}\n\n")

    return journal


def read_journal(run_number: int, project_dir: str | Path = ".") -> str | None:
    """Read the full journal for a run, or None if it doesn't exist yet.

    Args:
        run_number:  Sequential expedition run number.
        project_dir: Repo root; defaults to cwd.

    Returns:
        The full journal text, or None if the file doesn't exist.
    """
    journal = _journal_path(run_number, project_dir)
    if not journal.exists():
        return None
    return journal.read_text(encoding="utf-8")


def list_journals(project_dir: str | Path = ".") -> list[Path]:
    """Return all journal files sorted newest first.

    Args:
        project_dir: Repo root; defaults to cwd.

    Returns:
        List of Path objects for every expedition_NNNN.md in data/expeditions/.
    """
    base = Path(project_dir) / "data" / "expeditions"
    if not base.exists():
        return []
    return sorted(base.glob("expedition_*.md"), reverse=True)
